services:
    database:
        image: mariadb:11
        ports:
            - "3309:3306"
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: "express"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    express:
        image: node:23
        env_file:
            - ./.env
        ports:
            - "8090:3000"
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - ./app:/app
        command: 'sh -c "cd /app && npm run start"'
